spring:
  datasource:
    url: jdbc:mysql://192.168.92.137:3306/dick?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Jack@520
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.198.129
    timeout: 15000
    database: 2
    jedis:
      pool:
        max-active: 2000
        min-idle: 5
        max-idle: 20
        max-wait: 200
swagger:
  host: 127.0.0.1:9000